name: app

disk: 1024

type: "ruby:2.4"

hooks:
    build: |
        set -x

        [ -d "$PLATFORM_CACHE_DIR/bundle" ] && cp -rp "$PLATFORM_CACHE_DIR/bundle" vendor/bundle
        bundle install --deployment --verbose --without test --without development --retry 3 --jobs 4

        rm -rf "$PLATFORM_CACHE_DIR/bundle"
        cp -rp vendor/bundle "$PLATFORM_CACHE_DIR/bundle"
    deploy: bundle exec rake db:migrate

relationships:
    postgresql: "postgresql:postgresql"
    redis: "redis:redis"

mounts:
   "/log": "shared:files/log"
   "/tmp": "shared:files/tmp"
   "/public/uploads": "shared:files/uploads"
   "/public/plugins": "shared:files/plugins"
   "/public/assets": "shared:files/assets"
dependecies:
  nodejs:
    svgo: "*"
    phantomjs-prebuilt: "*"

web:
    upstream:
      socket_family: "tcp"
    commands:
       start: "UNICORN_PORT=$PORT bundle exec config/unicorn_launcher -E production -c config/unicorn.conf.rb"

    locations:
        "/":
            root: "public"
            passthru: true
            expires: 1h
            allow: true
        "/assets":
            root: "public/assets"
            expires: 1y
            allow: true
        "/plugins":
            root: "public/plugins"
            expires: 1y
            allow: true
        "/images/emoji":
            root: "public/images/emoji"
            expires: 1y
            allow: true
